# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nesdit < Formula
  desc "Edit structured config files with jq-style queries"
  homepage "https://sdkks.github.io/nesdit/"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sdkks/nesdit/releases/download/v0.3.2/nesdit_0.3.2_darwin_arm64.tar.gz"
      sha256 "7e8ebc0758154a2a251570e055d5bad8679adbab9f4a38385c24ecbc9c3f1e08"

      define_method(:install) do
        bin.install "nesdit"
        man1.install "share/man/man1/nesdit.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sdkks/nesdit/releases/download/v0.3.2/nesdit_0.3.2_linux_amd64.tar.gz"
      sha256 "b90319def400b0d391cf71343d9ce26be1afd432e4b620227f2941ec771a975c"
      define_method(:install) do
        bin.install "nesdit"
        man1.install "share/man/man1/nesdit.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sdkks/nesdit/releases/download/v0.3.2/nesdit_0.3.2_linux_arm64.tar.gz"
      sha256 "b9b71773ed493a70ece10998afd8e41384dcfea100ab14a200c207773494fcd2"
      define_method(:install) do
        bin.install "nesdit"
        man1.install "share/man/man1/nesdit.1"
      end
    end
  end

  test do
    system "#{bin}/nesdit", "--help"
  end
end
